name       : appstream
version    : 0.15.2
release    : 1
source     :
    - https://www.freedesktop.org/software/appstream/releases/AppStream-0.15.2.tar.xz : 8f6c1cd288c7c59f5bf21746a6cfd1424cd9d7cbeb0b7920dbcdf9ef10e9c74a
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.core
summary    : Tools and libraries to work with AppStream metadata
description: |
    AppStream is a cross-distro effort for enhancing the metadata available about software components in the Linux and free-software ecosystem. One of the project's goals is to make building software-center applications possible, and make interaction with the package sources of a distribution smarter. AppStream provides specifications for meta-information which is shipped by upstream projects and can be consumed by other software.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(xmlb)
    - pkgconfig(yaml-0.1)
    - gperf
    - itstool
    - libstemmer-devel
    - lmdb-devel
    - vala
setup      : |
    %meson_configure \
        --sysconfdir=/usr/share/appstream \
        -Dapidocs=false \
        -Dinstall-docs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
